version: "3.9"

services:
  app:
    build: .
    image: pflegeazubi
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npx expo start --web --port 8081 --no-dev
